### ISSUE TITLE
US4 Add Slider

### ISSUE THREAD

**Issue by Irazhap** [Irazhap/capstone-project#8]
## Value proposition

As a user, 
I would like a slide function,
so i can slide the list of movies horizontally

## Description

![Image](https://user-images.githubusercontent.com/92851229/236426635-37909c97-3c57-4ea5-96e5-9304de15fdf1.png)

## Acceptance criteria
- [ ] There are 4 carousels attached to the main page, which contain a list for each category: Popular, Now Playing, Upcoming, Top Rated.
- [ ] All lists must slide left and right, and at the End of the list, the carousel starts again from the beginning.

## Tasks

- [ ] Create a feature-branch 
- [ ] Install the react-slick and slick-carousel packages
- [ ] Modify the MovieList component to use the Slider component from react-slick

**Comment by mbosselmann** [comment]
Hi Irazhap,
well done, but I have some remarks and questions:

## Value Proposition
- for me it is not clear what the goal of this feature is: does it has to do with usability, a better overview or something like that? 🤔 

## Acceptance Criteria
- I don't think that this is the only criterion: what happens when you reach one end of the list or is it not a slider, but a carousel where at the end of the list you start again in the beginning when you reach the end?
- you should also describe what each slide in the description displays

## Tasks
Here I have another question: Have you discussed with your coaches, if you are allowed to user this package? Please discuss it with them before using react-slick for your capstone project. 👀

**Comment by Irazhap** [comment]
Hi Mareike,
**Value Proposition:** 
es ist auf der hauptseite, für eine bessere übersicht..

**Acceptance Criteria**
I corrected it a bit.

** Tasks**
yes, I got the okay from one of my coaches))
